### ISSUE TITLE
Adaptive Server connection failed (TinyTds::Error)

### ISSUE THREAD

**Issue by caverogustavo** [rails-sqlserver/tiny_tds#256] opened 2016-01-07 12:08 UTC
I face this error when I update the ruby version from 1.9.3 to 2.2.2. (OS win7)
The  version of tiny_tds 0.7.0
The  log error points to the error when the new connection is created 
conenction_db_chain = TinyTds::Client.new(:username=> $db_user, :password=> $db_usr_pass,
    :host=>$db_host, :port=>$db_port, :database=>$db_name, :azure=>true) 
db_host = somehost.database.windows.net
db_port = 1433
db_name = somedatabase

**Comment by metaskills** [comment] 2016-02-14 22:07
Our tests are on Windows, and use Azure too. So I know it works. What is the value of $db_user? Did you read this? https://github.com/rails-sqlserver/tiny_tds#using-tinytds-with-azure

**Comment by shawnemullen** [comment] 2016-02-15 01:19
Doesn't seem to work with AWS RDS.  Bummer.

**Comment by metaskills** [comment] 2016-02-15 03:13
It should work just fine. Have you tried the 0.9.5 pre release?

**Comment by shawnemullen** [comment] 2016-02-15 03:20
I tried the most recent version of tiny_tds.  I should clarify that I am running on linux, if that makes a difference.

**Comment by metaskills** [comment] 2016-02-15 03:22
Linux should work fine. Also, 0.7.0 is latest release... but 0.9.5.rc3 was released today. You really should try that. Lastly, remember, you need at least 0.9.5.80 of FreeTDS installed when linking TinyTDS. Check the README for full details.

**Comment by shawnemullen** [comment] 2016-02-15 03:27
From the READ.ME: "On all other platforms, we will find these dependencies. If none exist, our native extension will use MiniPortile to install any missing dependencies listed above for your specific platform."

To me this says I don't have to worry about what version of FreeTDS.  Is that not accurate?

**Comment by metaskills** [comment] 2016-02-15 03:31
Hmmm... a little. I think the OpenSSL dep installed by MiniPortile has only been tested for the native Windows builds. If you are on a POSIX capable of installing dependencies, I highly suggest that you do.

**Comment by metaskills** [comment] 2016-02-15 03:31
And by that, I mean when you install FreeTDS, that you link it against the latest OpenSSL too.

**Comment by shawnemullen** [comment] 2016-02-15 03:36
I'll take a look, but as a side note, I left Java and went to Ruby because I got tired of having to deal with dependencies and the constant headaches of having to track down version x of dependency y.  I like being able to type "gem install xxx" and it just works.

**Comment by metaskills** [comment] 2016-02-15 03:54
In the land of Ruby C-Extensions, this is not un-normal. Using your platform's package manager should be a benefit to you for more reasons than I can really convey here. I highly recommend that you separate Ruby and package managers  as a topic of headaches.

> went to Ruby because I got tired of having to deal with dependencies and the constant headaches of having to track down version x of dependency y

That's not fair rhetoric to put on me. It's not that bad man - honestly. This project is no different than using Ruby with MySQL, PostgreSQL, etc. Also, if you want to make [extconf.rb] work for your platform and get OpenSSL in, go for it. Just remember, when you compile gems that way -- static libs -- you will end up with memory bloat and potential crazy issues. Right now we have an issue with Windows pre-compiled binaries because of this technique. It is... un-natural. Cheers.

**Comment by shawnemullen** [comment] 2016-02-15 04:10
I think I may have not been clear.  I am not putting anything on you.   In general, I simply don't use gems that require me to hunt down dependencies.  If the gem has dependencies and it takes care of those for me, then I don't have issues with using it (as in using MiniPortile).  Yes, I have run into issues trying to stick to this,  but up until now I have been able to get around them.

I do realize that Ruby and package managers are separate issues.  but when they work nicely together it is definitely less of a headache.

Anyway, thanks for the quick responses to my questions.  If I have time to put this all together and make it work, I'll let you know how it goes.

**Comment by carolfly86** [comment] 2016-03-03 13:21
I have the same issue connecting to sql server database. But this only happens on the linux centos server, while works fine on my mac.  Also on the linux server it connects to other sql server instances fine. it's somehow only happening for this particular database instance.
TinyTds::Client.new username: 'dbmon', password: 'xxxxx', host: 's2-dba-102', port: '50002', database: 'tempdb'
TinyTds::Error: Adaptive Server connection failed
	from /var/lib/pgsql/.rvm/gems/ruby-2.1.1/gems/tiny_tds-0.7.0/lib/tiny_tds/client.rb:74:in `connect'
	from /var/lib/pgsql/.rvm/gems/ruby-2.1.1/gems/tiny_tds-0.7.0/lib/tiny_tds/client.rb:74:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /var/lib/pgsql/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'

I have freetds installed and tested the connection
TDDSVER=7.0 tsql -H s2-dba-102.s2.cvent.com -p 50002 -U dbmon
Password:
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
1>

Here's the content in /etc/freetds.conf

[global]
        # TDS protocol version
	tds version = 7.1
	dump file = /tmp/freetds.log
;	debug flags = 0xffff

	# Command and connection timeouts
;	timeout = 10
;	connect timeout = 10

# A typical Sybase server
[egServer50]
	host = symachine.domain.com
	port = 5000
	tds version = 5.0

# A typical Microsoft server
[s2-dba-102]
	host = s2-dba-102.s2.cvent.com
	port = 50002
	tds version = 7.1

tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v0.91
             freetds.conf directory: /etc
     MS db-lib source compatibility: yes
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 4.2
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no

Any idea where should I look for some more specific error msg ? I noticed nothing is logged in /tmp/freetds.log when executing TinyTds::Client.new username: 'dbmon', password: 'xxxxx', host: 's2-dba-102', port: '50002', database: 'tempdb'

**Comment by carolfly86** [comment] 2016-03-03 13:39
I have the problem fixed by uninstall and reinstall tiny_tds gem. I think it maybe that I have changed the freetds.conf (especially tds version=7.1 ) file after I first installed tiny_tds gem, and reinstalling forced it to use the new value?

**Comment by metaskills** [comment] 2016-03-08 00:38
Thanks @carolfly86 for following up.

**Comment by carolfly86** [comment] 2016-04-05 13:57
I was able to reproduce the issue on another centos vm. And seem like the solution is below:
1. yum install install freetds freetds-devel
2. reinstall 'tiny_tds' gem if it's already installed.
I was wrong in the previous post, the change in freetds.conf (update tds version from 4.2 to 7.1) is not relevant, and I don't really need to update freetds.conf.
Thanks @metaskills  it's a great tool!

**Closed** 2016-04-24 20:23 UTC
