### ISSUE TITLE
Unable to load tiny_tds in Windows 10

### ISSUE THREAD

**Issue by mbratch** [rails-sqlserver/tiny_tds#394] opened 2017-11-02 19:10 UTC
## Environment

Running Windows 10
Ruby version 2.3.3p222
Rails version 4.2.9
Using mingw64
Using DevKit-mingw64-64-4.7.2-20130224-1432

```
$ /c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/bin/tsql-ttds -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.27
             freetds.conf directory: C:/Sites
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: yes
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no
[TinyTds][v2.1.0][tsql]: C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/ports/i686-w64-mingw32/freetds/1.00.27/bin/tsql.EXE](url)
```

gem tiny_tds version 2.1.0

## Description

I had been using tiny_tds 1.3.0 which would intermittently give me an error described in the (now closed) ticket #365. However, recently, I was getting the problem more regularly with 1.3.0. I attempted using version 2.0.0, and saw the error every time. I know it sounds perhaps odd that 1.3.0 would work "intermittently" but it is true: without changing anything about my Rails setup, it would occasionally have this failure, but most of time it worked. I don't know if there's a possible intermittent loading failure of the DLL that it needs for freetds, and therefore the "require 'tiny_tds/tiny_tds'" fails?

More recently, it's been failing all the time with 1.3.0 which compelled me to explore the error further. Today I did more searching on this problem and found ticket #365 was closed, indicating that version 2.1.0 of tiny_tds fixes the issue. I installed version 2.1.0, but the issue still persists.

Error output:

```
$ irb
Switch to inspect mode.
>> require 'tiny_tds'
require 'tiny_tds'
LoadError: cannot load such file -- tiny_tds/tiny_tds
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:46:in `rescue in block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:43:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:37:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:34:in `block (2 levels) in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:24:in `rescue in block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:17:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:33:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:34:in `block (2 levels) in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:24:in `rescue in block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:17:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:33:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:34:in `block (2 levels) in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:24:in `rescue in block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:17:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:33:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:42:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from C:/RailsInstaller/Ruby2.3.3/bin/irb:11:in `<main>'
```

Here are the 'tiny_tds*' and 'freetds*' files in my installation:

```
$ find /c/RailsInstaller -name "tiny_tds*" -o -name "freetds*"
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/cache/tiny_tds-2.1.0-x86-mingw32.gem
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/doc/tiny_tds-2.1.0-x86-mingw32
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/ext/tiny_tds
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/ext/tiny_tds/tiny_tds_ext.c
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/ext/tiny_tds/tiny_tds_ext.h
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds/2.0/tiny_tds.so
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds/2.1/tiny_tds.so
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds/2.2/tiny_tds.so
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds/2.3/tiny_tds.so
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds/2.4/tiny_tds.so
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/tiny_tds.gemspec
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/specifications/tiny_tds-2.1.0-x86-mingw32.gemspec

/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-1.3.0-x86-mingw32/ports/patches/freetds
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/patches/freetds
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/ports/i686-w64-mingw32/freetds
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/ports/i686-w64-mingw32/freetds/1.00.27/bin/freebcp.exe
/c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/tasks/ports/freetds.rb

$ ls -l /c/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/ports/i686-w64-mingw32/freetds/1.00.27/lib
total 156
-rw-r--r-- 1 mbratc01 1049089  46508 Nov  2 16:24 libct.dll.a
-rw-r--r-- 1 mbratc01 1049089   1315 Nov  2 16:24 libct.la
-rw-r--r-- 1 mbratc01 1049089 100968 Nov  2 16:24 libsybdb.dll.a
-rw-r--r-- 1 mbratc01 1049089   1327 Nov  2 16:24 libsybdb.la
```
## Mitigation
The failure point is line 46 in tiny_tds.rb, where it does "require 'tiny_tds/tiny_tds'". In order to resolve this problem, I could start there and look to see if all of the requisite files are where they need to be. But I need help understanding what and where those requisite files are.

**Comment by coderjoe** [comment] 2017-11-04 16:45
@mbratch sorry for the delay. I believe this might be a duplicate of #391 . Could you please do the following to help me confirm?

1. Ensure devkit is installed for your version of ruby.
2. run irb
3. `require 'devkit'`
4. `require 'tiny_tds'`

If I am correct requiring devkit prior to requiring tiny_tds should resolve your issue when devkit is installed.

**Comment by mbratch** [comment] 2017-11-06 17:50
@coderjoe  I think you hit the nail on the head. When I did the `require 'devkit'` it succeeded but indicated, "Temporarily enhancing PATH to include DevKit...". The subsequente `require 'tiny_tds'` succeeded. So I'm thinking I need a DevKit something or other in my PATH. The question is: what subdir of `DevKit` should go in the path? I tried including `C:\DevKit\bin` and `C:\DevKit\mingw\bin`, but I still get the original error, and this test still says Temporarily enhancing PATH to include DevKit...".

**Comment by coderjoe** [comment] 2017-11-06 20:04
Your best bet is to just `require 'devkit'` at the start of your project prior to requiring tiny_tds.

In the event that won't work you can take a look at the devkit.rb shim that devkit installs to find out what it's doing to the path.

I'm currently experimenting with some options for working around this problem within the gem, and it looks like the best option might be one proposed by @aharpervc in the linked issue above.

In the mean time, I think I'm going to close this issue as a duplicate. Please follow #391 to keep track of the status of the fix!

**Closed by coderjoe** 2017-11-06 20:04 UTC

**Comment by mbratch** [comment] 2017-11-06 20:26
@coderjoe ok, thank you. I'll take that approach and track #391.
