### ISSUE TITLE
Tiny_TDS doesn't include pre-compiled native gems for x64 Ruby on Windows.

### ISSUE THREAD

**Issue by edward-ellis** [rails-sqlserver/tiny_tds#323] opened 2016-12-02 00:12 UTC
I am using Tiny TDS on Windows 10 with Ruby 2.1.7 x64.  All my gems work except tiny_tds.  If I switch to the x86 version of Ruby all is well.  Do you intend to support x64 Ruby versions on Windows?

**Comment by edward-ellis** [comment] 2016-12-02 00:13
If you don't intend to support x64, at least indicate that in the README.

**Comment by metaskills** [comment] 2016-12-02 00:52
It was my understanding that we always supported 64-bit windows for all Ruby versions we support including 2.1. Till recently we had builds on Appveyor for multiple x64 versions. Even those only one for 2.3 remains, the others should still work fine.

* https://github.com/rails-sqlserver/tiny_tds/blob/master/Rakefile#L97
* https://github.com/rails-sqlserver/tiny_tds/blob/master/appveyor.yml#L40-L41

Could you investigate a bit more and let me know what you find.

**Comment by coderjoe** [comment] 2016-12-02 01:04
When working on PR #322 I could have sworn I saw it building x64 binaries.

**Comment by metaskills** [comment] 2016-12-02 01:10
You did!

**Comment by edward-ellis** [comment] 2016-12-02 01:20
Ok, I don't really understand the internal workings of installing gems. All I know is that only the .so version gets installed. Can you give me some guidance on how to gather information that would be useful to you?

**Comment by metaskills** [comment] 2016-12-02 01:39
Sure, maybe start with a few things and we can go from there.

* What version of TinyTDS are you using? Do have the same problem with other versions?
* For the version you are having issues with, if you bundle open the gem, what do you see in the lib/tiny_tds dir?

**Comment by edward-ellis** [comment] 2016-12-02 17:15
I am using tiny_tds_1.0.5-x64-mingw32.  I haven't other versions yet today.  In the lib/tiny_tds dir I see:

- bin.rb
- client.rb
- error.rb
- result.rb
- version.rb
- 2.0
-- tiny_tds.so
- 2.1
-- tiny_tds.so
- 2.2
-- tiny_tds.so
- 2.3
-- tiny_tds.so

**Comment by edward-ellis** [comment] 2016-12-02 17:24
I have installed 1.0.3 and 1.0.0 and get the same results.  For bundle open I still only get the tiny_tds.so.

**Comment by coderjoe** [comment] 2016-12-03 00:33
Each of those are libraries cross compiled for the windows architecture and runtime in their gem package name. As an example here's a file inspection from my recent testing build:

```
coderjoe@pulsar:public/tiny_tds/pkg[openssl-1.0.2j]% ls
tiny_tds-1.0.6/     tiny_tds-1.0.6-x64-mingw32/     tiny_tds-1.0.6-x86-mingw32/
tiny_tds-1.0.6.gem  tiny_tds-1.0.6-x64-mingw32.gem  tiny_tds-1.0.6-x86-mingw32.gem
coderjoe@pulsar:public/tiny_tds/pkg[openssl-1.0.2j]% file tiny_tds-1.0.6-x64-mingw32/lib/tiny_tds/2.3/tiny_tds.so 
tiny_tds-1.0.6-x64-mingw32/lib/tiny_tds/2.3/tiny_tds.so: PE32+ executable (DLL) (console) x86-64, for MS Windows
coderjoe@pulsar:public/tiny_tds/pkg[openssl-1.0.2j]% file tiny_tds-1.0.6-x86-mingw32/lib/tiny_tds/2.3/tiny_tds.so 
tiny_tds-1.0.6-x86-mingw32/lib/tiny_tds/2.3/tiny_tds.so: PE32 executable (DLL) (console) Intel 80386, for MS Windows
coderjoe@pulsar:public/tiny_tds/pkg[openssl-1.0.2j]%
```

What problem are you experiencing that lead you to investigate these binaries?

**Comment by coderjoe** [comment] 2016-12-16 00:09
@edward-ellis can you provide any extra information?

**Comment by edward-ellis** [comment] 2016-12-19 22:42
Yes, I found it confusing that the DLLs were given a Linux suffix, but I suppose that is just a convenience for the developers.  I also started asking questions on gitter.im and @coderjoe suggested that this is the same problem as issue #310.  It certainly sounds like the "tiny_tds.so not a valid win32 application" part of that issue.  They were suggesting that version 1.0.6 might fix that issue, but that has yet to be released.

**Comment by metaskills** [comment] 2016-12-19 23:55
Once #324 is resolved, I plan to release v1.1 using the new versions of all the good things. I really do help this helps.

**Comment by metaskills** [comment] 2016-12-20 02:54
Just wanted to report, I am seeing the same issue on the adapter tests in Appveyor which use the Windows pre-compiled gems. The `-x64` Ruby versions shows this error for v1.0.5 of TinyTDS

```
`require': cannot load such file -- tiny_tds/tiny_tds (LoadError)
```

I did find that v1.0.4 did seems to work so I think this is an issue with v1.0.5.

**Comment by coderjoe** [comment] 2016-12-20 03:02
@metaskills that sounds a lot like the invalid win32 executable problem my PR tries to address. You can verify this on appveyor by running the build and enabling RDP via: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

If you log into the instance you can verify the problem is the same by testing to make sure tiny_tds can be required if it is the only required gem, but it will likely fail if yaml (or psych.so) are loaded first).

If it matches, there's a good chance that my already merged PR will solve your problem. You can also try testing with the tiny_tds_coderjoe gem which I used for testing and plan to yank once 1.0.6 or 1.1.0 are out.

**Comment by metaskills** [comment] 2016-12-20 17:13
I just released v1.1.0 (thanks @coderjoe) and it appears to fix the x64 issues on Appveyor. Please confirm it helps here too.

**Comment by arbesulo** [comment] 2016-12-21 15:19
I have just updated and I'm getting "the specified module could not be found tiny_tds.so" when requiring `tiny_tds/2.3/tiny_tds`

The problem does not arise with 1.0.4

**Comment by coderjoe** [comment] 2016-12-21 15:38
@arbesulo please use `require 'tiny_tds'` it will make sure to load the appropriate library for your ruby version for you.

**Comment by arbesulo** [comment] 2016-12-21 16:01
That's what I'm doing. I just pointed where the error happens, because it is shadowed by the `rescue LoadError` 2 lines below.

**Comment by coderjoe** [comment] 2016-12-21 16:36
@arbesulo would you mind providing the full stacktrace as well as a reproduction and your machine's architecture? Thanks. :)

**Comment by arbesulo** [comment] 2017-01-06 09:00
Sorry for the delay, I was on holidays 

I'm using ruby 2.3.3p222 (i386-mingw32), Rails 3.2.22.1 on a Windows Server 2012 (testing version on a VM)


The stacktrace is following:

```
Z:\>rails c
C:/Ruby23/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- tiny_tds/tiny_
tds (LoadError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/tiny_tds-1.1.0-x86-mingw32/lib/tiny_tds.rb:22:in `rescue in <top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/tiny_tds-1.1.0-x86-mingw32/lib/tiny_tds.rb:25:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
        from Z:/config/application.rb:31:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-3.2.22.1/lib/rails/commands.rb:39:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-3.2.22.1/lib/rails/commands.rb:39:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'

```

**Comment by stibra** [comment] 2017-01-10 13:55
I have the same error "LoadError: cannot load such file -- tiny_tds/tiny_tds", with x64 Ruby 2.2.3 and tiny_tds 1.1.0.

**Comment by Jonny-B** [comment] 2017-01-31 16:22
I am seeing this too. Just updated to x32 Ruby 2.2.3 and tiny_tds 1.1.0

cannot load such file -- tiny_tds/tiny_tds (LoadError)
C:/Ruby23/Ruby23/lib/ruby/gems/2.3.0/gems/tiny_tds-1.1.0-x86-mingw32/lib/tiny_tds.rb:22:in `require'
C:/Ruby23/Ruby23/lib/ruby/gems/2.3.0/gems/tiny_tds-1.1.0-x86-mingw32/lib/tiny_tds.rb:22:in `rescue in <top (required)>'
C:/Ruby23/Ruby23/lib/ruby/gems/2.3.0/gems/tiny_tds-1.1.0-x86-mingw32/lib/tiny_tds.rb:25:in `<top (required)>'

**Comment by coderjoe** [comment] 2017-02-03 15:15
@stibra and @Jonny-B  can you please update with your operating system versions and architectures please?

**Comment by stibra** [comment] 2017-02-03 15:18
Win2012R2 server and Win2016 server

Sent from my iPad

On 3 Feb 2017, at 16:15, Joe Bauser <notifications@github.com<mailto:notifications@github.com>> wrote:


@stibra<https://github.com/stibra> and @Jonny-B<https://github.com/Jonny-B> can you please update with your operating system versions and architectures please?

-

**Comment by stibra** [comment] 2017-02-14 13:32
Any news on this issue?

**Comment by coderjoe** [comment] 2017-02-14 23:16
@stibra I appreciate the question. I'm still looking into this in my free time, but it's not currently related to any roadmap items at my company so I only have an hour or two every few weekends of free time to expend. I intend to keep moving along but my time is extremely limited right now.

If anybody needs this fixed faster PRs are, as always, very welcome. :)

**Comment by metaskills** [comment] 2017-03-12 16:55
Pull Request #347 pulled in OpenSSL v1.1.0 and we got new versions of TinyTDS at v1.2.0 which should solve this issue. Please reply back and let us know.

**Closed by metaskills** 2017-03-12 16:55 UTC
