### ISSUE TITLE
Connect MSSQL using Windows Authentication

### ISSUE THREAD

**Issue by shinejikids** [rails-sqlserver/tiny_tds#236] opened 2015-11-05 10:19 UTC
I have a problem with connecting MSSQL server using Windows Authentication. This is my code:

```ruby
con = TinyTds::Client.new(:username => 'GLOBAL\username', :host => 'MYHOST', :database => 'MYDB')
```

In freetds.conf
```
[MYHOST]
        host = 123.45.6.7
        port = 1433
```

```
TinyTds::Error: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
  from /home/foobar/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tiny_tds-0.6.2/lib/tiny_tds/client.rb:77:in `connect'
  from /home/foobar/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tiny_tds-0.6.2/lib/tiny_tds/client.rb:77:in `initialize'
  from (irb):4:in `new'
  from (irb):4
  from /home/foobar/.rbenv/versions/2.1.5/bin/irb:11:in `<main>'
```

Are options correct? Anyone have any ideas on how to fix?
Thanks

**Comment by metaskills** [comment] 2015-11-09 13:28
This is a duplicate of #221. Windows authentication is not supported in FreeTDS yet.

**Closed** 2015-11-09 13:28 UTC

**Comment by larskanis** [comment] 2015-11-10 20:28
Kerberos authentication should work since FreeTDS-9.1 according to the [NEWS file](https://github.com/FreeTDS/freetds/blob/ea64a79533dad44c717d7b9764d6d97c8f925c58/NEWS#L86) . But the computer must be joined to the domain of the SQL-Server, see [FreeTDS documentation](http://www.freetds.org/userguide/kerberos.htm). Even if Microsoft calls this Windows authentication, it isn't limited to Windows by any means. I use this kind of SSO with our PostgreSQL servers and clients cross platform since years. But this is not the same as Azure Active Directory Authentication.

**Comment by zhongxiao37** [comment] 2016-06-08 10:01
The error message says you were doing things cross domain, which is not allowed. You need to use credentional manager to get it resolved. Try this doc: https://www.mssqltips.com/sqlservertip/3250/connect-to-sql-servers-in-another-domain-using-windows-authentication/. However, I don't have this problem on Mac even I'm on other domains.
