### ISSUE TITLE
Occasional Adaptive Server connection failed

### ISSUE THREAD

**Issue by archnnj** [rails-sqlserver/tiny_tds#301] opened 2016-09-21 10:01 UTC
I have a ruby script that performs queries in loop to several Sql Server 2014 databases (about 100 DBs and 5 queries for each of them).
It is currently running on a Windows Server 2012 R2 Standard machine with Ruby 2.1.5, while the DBs are on another machine (with the same OS).

The script was working fine until a month ago when, after some routine Windows updates on the DB machine, it started to occasionally crash for the following error:

```
--- !ruby/exception:TinyTds::Error
message: Adaptive Server connection failed (<my-ip>:<my-port>)
severity: 9
db_error_number: 20002
os_error_number: 
source: error
```

This usually happens at least once per loop, on different databases and without a pattern, so I don't think it depends on a particular DB configuration.

Has anybody experienced this before? Do you know how to fix it?

**Comment by metaskills** [comment] 2016-09-21 12:28
Odd! Can you tell me what version of TinyTDS you are using and what version of FreeTDS you have linked to using `tsql -C`

**Comment by archnnj** [comment] 2016-09-23 13:24
I was using TinyTDS 0.7.0 because of another issue, but I tried it also with TinyTDS 1.0.4 and it still happens.
I haven't set up FreeTDS so I think I'm running the default version: should I recompile something?

I tried to run `tsql -C`, but I get a System Error alert saying:
"The program can't start because libeay32-1.0.2g-x86_64-w64-mingw32.dll is missing from your computer. Try reinstalling the program to fix this problem.". 
Could it be related? You can see the error in the attachment. I already tried to reinstall the gems and even Ruby, but nothing changes.

![screen shot 2016-09-23 at 15 12 32](https://cloud.githubusercontent.com/assets/20643285/18786842/3a09ba52-81a0-11e6-870b-f06d0a083500.png)

**Comment by metaskills** [comment] 2016-09-23 23:14
Don't sweat the tsql -C. I've never really tested that delegate bin wrapper on Windows. Still can't offer any advice on the root issue you are having. Have you browsed the other issues?

**Comment by archnnj** [comment] 2016-09-29 15:41
Oh ok, I didn't think the tsql -C issue was related indeed.
I browsed all the other issues on this repo but nothing seems close to my problem.
I'll wait a bit more to see if someone else is experiencing similar issues, otherwise I guess I'll have to think about a more drastic solution.
Thanks for the assistance anyway!

**Comment by schneikai** [comment] 2016-10-04 11:42
Just to let you know guys we are experiencing this issue too since last Wednesday (9/28/2016). TinyTDS 0.6.2
Rails 4.0.4
Ruby 1.9.3
Connection is made from Ubuntu 12.04.5 LTS to Windows Web Server 2008 R2 running SQL Server 2005.

The error is TinyTds::Error Adaptive Server connection failed in .../bundle/ruby/1.9.1/gems/tiny_tds-0.6.2/lib/tiny_tds/client.rb:77:in connect

We never had this errors before. They just started to appear about one error every other minute.

I wanted to try updating TinyTDS now and see if this will fix things...

**Comment by sngeth** [comment] 2016-10-05 14:20
August 28 we had a green build on Jenkins. Same branch no longer passes due to errant Adaptive Server Connection failed. So roughly in a month something problematic also seems to have occurred for us.

Rails 4.2 app using Ruby 2.1
tiny_tds gem version 0.51 and freetds 0.91
Databases are running via SQL Server 2014 on a Windows Server 2012

**Comment by metaskills** [comment] 2016-10-06 00:16
@sngeth @schneikai What are your thoughts on how it could be something in this gem? Did you have no issues in versionX and now you do in versionY? Where is the change to isolate the problem? Also, have y'all tried to use the latest FreeTDS v1.00.x and then install the latest TinyTDS v1.x to work with it? Seems y'all are both on a really old version(s).

**Comment by schneikai** [comment] 2016-10-06 07:59
Yeah, I don't think it's related to this Gem or FreeTDS. Nothing changed in our setup when these errors started popping up. I suspect something was changed in SQL Server via a Windows Update...

**Comment by metaskills** [comment] 2016-10-06 11:32
> suspect something was changed in SQL Server via a Windows Update
> don't think it's related to this Gem or FreeTDS

Thanks. Might I suggest trying to upgrade to FreeTDS 1.00.x and the latest TinyTDS and let me know how that goes?

**Comment by neongrau** [comment] 2016-10-06 13:11
Is there a reommended version of TinyTDS to use with Rails 4.2.5 and SQLServer-Adapte 4.2.15 on Windows?
When i recently tried TinyTDS 1.00.x my Thin server refused to start when trying to run as a service due to a problem with TinyTDS. I had to downgrade to 0.7.0 which was the latest version that worked for me.

**Comment by schneikai** [comment] 2016-10-06 13:46
@metaskills Can't upgrade unfortunately because we are stuck with ruby 1.9.3 for the moment and latest TinyTDS requires >= 2.0 right?

**Comment by sngeth** [comment] 2016-10-06 14:21
Small update:

Just upgraded tiny_tds from 0.51 to 1.04 and freetds from 0.91 to 0.95.81 (latest CentOS package that was available) and the errors still occurred.

**Comment by sngeth** [comment] 2016-10-06 15:33
So I decided to isolate the offending code right before the connection fails that attempts to make a new connections:
```
def truncate_db_tables
  DB.each_server do |db|
    tables_to_truncate = db['SELECT DISTINCT
    t.NAME AS TableName
FROM 
    sys.tables t
INNER JOIN 
    sys.partitions p ON t.object_id = p.OBJECT_ID

where p.rows > 0']
    tables_to_truncate.to_a.each {|table| db.from(table[:tablename]).truncate unless table[:tablename].downcase == "homecontent"}
  end
end
```

When I remove the call to the above method the errors have disappeared. I noticed @archnnj mentioned his script he wrote also dealt with looping through databases so I wonder if that might a clue...

**Comment by metaskills** [comment] 2016-10-06 17:10
> Is there a reommended version of TinyTDS to use with Rails 4.2.5 and SQLServer-Adapte 4.2.15 on Windows?

@neongrau Always latest. FreeTDS is at v1.00.15 now and TinyTDS is at 1.0.4.

**Comment by metaskills** [comment] 2016-10-06 17:10
> Can't upgrade unfortunately because we are stuck with ruby 1.9.3 for the moment and latest TinyTDS requires >= 2.0 right?

@schneikai Correct. Might be time to get off 1.9 now too ;)

**Comment by metaskills** [comment] 2016-10-06 17:12
> from 0.91 to 0.95.81

@sngeth That's not "that" bad of a version, but so much work was done to FreeTDS as it closed in to the 1.0 release. I really do recommend the latest be installed somehow. I use MacPorts and just had to use my own Portfile. There has to be a way for CentOS too.

**Comment by sngeth** [comment] 2016-10-08 00:12
Update: I installed FreeTDS 1.0 and the errors still appeared.

Seems the issue is a bit insidious and may be dependent on application usage code. I removed the code that seems to trigger the connection failure. In my case it was a method call truncating multiple databases after each cucumber scenario
```
def truncate_db_tables
  DB.each_server{|db| #truncate tables here} #DB is the Sequel object that holds connections to the dbs
end
```

I replaced the above with database_cleaner gem to do the work and the errors have disappeared. My only caveat is I have to use a single test database as I haven't figured out how to clean multiple databases.

Unfortunately none of this really explains why things used to work. I think the last thing I could try is to rollback Windows to around the time the branch had previously passed. I didn't notice any updates to SQL Server mostly Windows Server critical/security updates.

**Comment by metaskills** [comment] 2016-10-09 16:33
It is highly possible that your `DB` (assuming that is a client instance) may not be used in a thread safe manner? Very easy to do with high level testing.

**Comment by metaskills** [comment] 2016-10-09 19:01
Made a note here about thread-safety. https://github.com/rails-sqlserver/tiny_tds/commit/7690dfa5511d4b78096fc8adbae7c1b7b28cd280

**Closed by metaskills** 2016-10-09 19:01 UTC
Labels: more-info

**Comment by ewales** [comment] 2016-11-29 22:04
We have been having this issue too since we migrated our Microsoft SQL database to a new server (Latest Server 2012 AMI from amazon with a manual install of SQL 2008). Right now we get a few hundred errors a day in numerous places in the code and I haven't been able to reliably reproduce. 
Versions:
Ruby: 1.9.3
tiny_tds: 0.6.2 (Updating to 0.7.0 now but not feeling confident this will solve the issue based on other comments)
FreeTDS: 0.91-6+b1

@metaskills Implementing connection_pool did not solve the issue

@schneikai Were you able to fix this, we are trapped in 1.9.3 for the moment as well

**Comment by schneikai** [comment] 2016-11-30 09:24
Unfortunately no. I just rescue and retry.

**Comment by llyons** [comment] 2017-02-15 16:21
Was anybody able to solve this?  We are also having this issue since an upgrade to sql2014.

**Comment by ewales** [comment] 2017-03-24 05:46
@llyons Sadly we just implemented retrys. Hoping to do an upgrade to Ruby 2.x later this year in part to see if it improves this issue.
