### ISSUE TITLE
Assertion failed: tds->state < TDS_VECTOR_SIZE(state_names), file util.c, line 95

### ISSUE THREAD

**Issue by csoop** [rails-sqlserver/tiny_tds#170] opened 2014-09-12 04:00 UTC
Assertion failed: tds->state < TDS_VECTOR_SIZE(state_names), file util.c, line 9
5

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by dicom** [comment] 2015-07-01 10:24
I can confirm that this issue is real.

I am getting this error consistently in my rails application which uses tiny_tds to extract some information from a database and display it in the browser. It doesn't seem to happen in a deterministic manner though, but ever since I rewrote my application (and increased the workload somewhat), it has started happening pretty often (more than once a day), and become a real nuisance. When it occurs, my rails application completely shuts down with the following error:

    Assertion failed!

    Program: C:\ruby\bin\ruby.exe
    File: util.c, Line 95

    Expression: tdsd->state < TDS_VECTOR_SIZE(state_names)

    This application has requested the Runtime to terminate it in an unusual way.
    Please contact the application's support team for more information.

Some system info:
OS: Windows 7 Professional Service Pack 1 (64 bit)
Ruby: 2.1.5p273 [i386-mingw32]
tiny_tds: 0.6.2 x86-mingw32

I am quite interested in getting this issue fixed, and I welcome any instruction on how I can help by producing better debug information, if possible.

![image](https://cloud.githubusercontent.com/assets/68168/8452532/ff42a206-1feb-11e5-8978-9b3f66babe31.png)

**Comment by dicom** [comment] 2015-07-06 13:09
@metaskills Do you have any thoughts on this?
(the issue is getting somewhat annoying for me unfortunately)

**Comment by metaskills** [comment] 2015-07-08 12:24
Damn... sorry! This could be a FreeTDS bug that is fixed in recent version. I really need to find some time to pick this ticket up https://github.com/rails-sqlserver/tiny_tds/issues/196

**Comment by metaskills** [comment] 2015-08-03 11:15
I am going to close this out. We have done a 0.6.3.rc2 pre-release which overhauls the Windows builds. This pre-release will become our 0.7.0 version by end of this week. Please give it a test run and let us know. Also, throw some props to @larskanis for his great work on the Windows builds.

**Closed by metaskills** 2015-08-03 11:15 UTC
Labels: bug

**Comment by d-plourde** [comment] 2020-05-28 16:01
Curious if anyone found the cause of the issue or if it was actually fixed with you integrating a newer version of FreeTDS? Memory overflow writing to the state?
