### ISSUE TITLE
TinyTds::Error: Cannot insert the value NULL into column 'COL_NAME', table 'TABLE NAME'; column does not allow nulls. INSERT fails.

### ISSUE THREAD

**Issue by mrdougwright** [rails-sqlserver/tiny_tds#248] opened 2015-12-07 20:08 UTC
I'm running a simple read sql procedure: `@client.execute(sql_procedure)` and getting the following error. Any ideas?

**Comment by metaskills** [comment] 2015-12-08 00:00
Hey! Thanks for using the gem. I am almost certain that a) I do not have enough information to help and b) that this is not a TinyTDS issue. I recommend that you debug the procedure in SQL Server Management studio or something. For example if `sql_procedure` is a string which is something like `"EXEC dbo.uspGetEmployeeManagers 6"` then paste that into a query window and find out what happens. 

Hope that helps, closing this issue but feel free to post back when you find more.

**Closed by metaskills** 2015-12-08 00:00 UTC

**Comment by mrdougwright** [comment] 2015-12-08 00:13
After talking with some other devs, you're absolutely right. It's a SQL Server problem. Thanks for the quick response!

**Comment by ttilberg** [comment] 2017-03-02 20:01
Hey @metaskills - First, I very much appreciate the work you do, and I apologize if this message is inappropriate. 

I'm running into a similar thing @mrdougwright  described, but they didn't give any info after it was solved. I wanted to post more here before opening a full new issue as I'm unsure if this is a legit bug or if I'm doing it wrong.

First I'll show my original use, and then below some more specific testing seeming to isolate `tiny_tds`.

This issue bubbled up while executing a sproc for compiling flat files to be delivered. Within, it creates a temp table, to hold the final output. In doing more investigation, it seems like it doesn't need to be buried in a sproc, or in a temp table, and instead appears with very basic usage. If you could provide any insight (or maybe it's a bug) I would be appreciative.

The original error while using: 
- `SQL Server 2016`
- `ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]`
- `tiny_tds (1.0.5)`
- `sequel (4.41.0)`

```
$ ruby thursday_deliveries.rb
2017-03-02 13:26:15 -0600 ========================
2017-03-02 13:26:15 -0600 Generating prices. This will take a while.
/home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:218:in `fields': TinyTds::Error: Cannot insert the value NULL into column 'tire_category', table 'tempdb.dbo.#custom_out_________________________________________________________________________________________________________0000000003EA'; column does not allow nulls. INSERT fails. (Sequel::NotNullConstraintViolation)
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:218:in `block in fetch_rows'
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:65:in `block in execute'
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:34:in `execute'
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:970:in `execute'
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:217:in `fetch_rows'
        from /home/ttilberg/.rvm/gems/ruby-2.2.5/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:141:in `each'
        from /mnt/c/Users/Tim/dev/rb/file_deliveries/csv_export.rb:38:in `each_with_object'
        from /mnt/c/Users/Tim/dev/rb/file_deliveries/csv_export.rb:38:in `block in write'
        from /mnt/c/Users/Tim/dev/rb/file_deliveries/csv_export.rb:28:in `open'
        from /mnt/c/Users/Tim/dev/rb/file_deliveries/csv_export.rb:28:in `write'
        from thursday_deliveries.rb:24:in `block in run'
        from thursday_deliveries.rb:19:in `each'
        from thursday_deliveries.rb:19:in `run'
        from thursday_deliveries.rb:34:in `<main>'
```


A good sample query to demonstrate:
```sql
CREATE TABLE #test (can_be_null nvarchar(255));

INSERT INTO #test(can_be_null)
VALUES (NULL);

SELECT can_be_null
FROM #test;

DROP TABLE #test;
```

I ran this against both SQL Server 2012 and 2016 and came up with the same results. Below I'm showing results from SSMS, tsql cli app, and in ruby code from `TinyTds::Client`

I then used Docker to ensure this isn't related to old versions of ruby, and it still happens in the current release. Below are my sample results:

SSMS succeeds:
![image](https://cloud.githubusercontent.com/assets/7969650/23523536/f59ca3d6-ff4c-11e6-828c-b83b210683fd.png)


#### Use a fresh install to eliminate potential old version problems

```
C:\Users\Tim\Tire Pricing\tire-pricing (master)
λ docker run -it --rm ruby:latest bash

root@6af1deff50c1:/# ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

root@6af1deff50c1:/# which ruby
/usr/local/bin/ruby

root@6af1deff50c1:/# gem install pry
Fetching: coderay-1.1.1.gem (100%)
Successfully installed coderay-1.1.1
Fetching: slop-3.6.0.gem (100%)
Successfully installed slop-3.6.0
Fetching: method_source-0.8.2.gem (100%)
Successfully installed method_source-0.8.2
Fetching: pry-0.10.4.gem (100%)
Successfully installed pry-0.10.4
4 gems installed


root@6af1deff50c1:/# gem install tiny_tds
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: tiny_tds-1.1.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed tiny_tds-1.1.0
2 gems installed

root@6af1deff50c1:/# gem list tiny_tds

*** LOCAL GEMS ***

tiny_tds (1.1.0)
```

#### TSQL info and tests
```
root@6af1deff50c1:/# tsql -C
[TinyTds][v1.1.0][tsql]: /usr/local/bundle/gems/tiny_tds-1.1.0/exe/tsql
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.21
             freetds.conf directory: /usr/local/bundle/gems/tiny_tds-1.1.0/ports/x86_64-pc-linux-gnu/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no

root@6af1deff50c1:/# tsql -S 192.168.20.46 -p 1433 -U user -P password
[TinyTds][v1.1.0][tsql]: /usr/local/bundle/gems/tiny_tds-1.1.0/exe/tsql
locale is "C"
locale charset is "ANSI_X3.4-1968"
using default charset "ISO-8859-1"
1> SELECT @@VERSION VersionInfo
2> GO
VersionInfo
Microsoft SQL Server 2012 - 11.0.2218.0 (X64)
        Jun 12 2012 13:05:25
        Copyright (c) Microsoft Corporation
        Standard Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)

(1 row affected)
1> exit

root@6af1deff50c1:/# tsql -S 192.168.20.46 -p 1433 -U user -P password
[TinyTds][v1.1.0][tsql]: /usr/local/bundle/gems/tiny_tds-1.1.0/exe/tsql
locale is "C"
locale charset is "ANSI_X3.4-1968"
using default charset "ISO-8859-1"
1> create table #test (can_be_null nvarchar(255)); insert into #test(can_be_null) values (null); select can_be_null from #test; drop table #test;
2> go
can_be_null
NULL
(1 row affected)
1> exit

```

#### TinyTds::Client in ruby code -- fails when insert null to #temp table

```
root@6af1deff50c1:/# pry
[1] pry(main)> require 'tiny_tds'
=> true

[2] pry(main)> client = TinyTds::Client.new(host: "192.168.20.46", username: "user", password: "password", database: "tim")
=> #<TinyTds::Client:0x00000001f4f0c8
 @query_options={:as=>:hash, :symbolize_keys=>false, :cache_rows=>true, :timezone=>:local, :empty_sets=>true}>

[3] pry(main)> sql = 'create table #test (can_be_null nvarchar(255)); insert into #test(can_be_null) values (null); select can_be_null from #test; drop table #test;'
=> "create table #test (can_be_null nvarchar(255)); insert into #test(can_be_null) values (null); select can_be_null from #test; drop table #test;"

[4] pry(main)> result = client.execute sql
=> #<TinyTds::Result:0x00000002023d78
 @query_options={:as=>:hash, :symbolize_keys=>false, :cache_rows=>true, :timezone=>:local, :empty_sets=>true}>

[5] pry(main)> result.do
TinyTds::Error: Cannot insert the value NULL into column 'can_be_null', table 'tempdb.dbo.#test_______________________________________________________________________________________________________________0000000000C9'; column does not allow nulls. INSERT fails.
from (pry):5:in `do'

[6] pry(main)> exit

```

To ensure this table is defined as I expected, I both generated scripts to see what the default "nullability" was when it wasn't initially specified, and also checked `[tempdb].[INFORMATION_SCHEMA].[COLUMNS]` which lists `IS_NULLABLE` as `YES`

At this point I'm not sure where to look next, other than updating a few dozen sprocs on my db to explicitly define `null` in the create table statements. Not that being explicit in the definition is bad...

Am I doing something wrong, or is there potentially a bug?

**Comment by metaskills** [comment] 2017-03-03 01:04
I think the issue is that a pure DBLIB connection needs a few sane configurations set. We do this in the ActiveRecord adapter for TinyTDS. Given that you are connecting to a non-Azure, these lines standout.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver_adapter.rb#L373-L379

```ruby
>> client = TinyTds::Client.new host: 'localhost', username: 'sa', password: ENV['SA_PASSWORD']
>> client.execute('SET ANSI_DEFAULTS ON').do
>> client.execute('SET CURSOR_CLOSE_ON_COMMIT OFF').do
>> client.execute('SET IMPLICIT_TRANSACTIONS OFF').do
>> client.execute('SET TEXTSIZE 2147483647').do
>> client.execute('SET CONCAT_NULL_YIELDS_NULL ON').do
>> client.execute("create table #test (can_be_null nvarchar(255))").do
>> client.execute("insert into #test(can_be_null) values (null);").do
=> 1
>>
```

So that works where without the SETs it would fail like this:

```ruby
TinyTds::Error: Cannot insert the value NULL into column 'can_be_null', table 'tempdb.dbo.#test_______________________________________________________________________________________________________________000000000003'; column does not allow nulls. INSERT fails.
	from (irb):11:in `do'
	from (irb):11
	from /Users/kencollins/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

**Comment by ttilberg** [comment] 2017-03-03 15:54
Thank you!

It is the `SET ANSI_DEFAULTS ON` that made the difference. It must be tied to `SET ANSI_NULL_DFTL_ON`.

I wonder if some of these similar "sane defaults" would make sense to suggest to the `Sequel` gem team in their `tinytds adapter`-- that's where this issue originally popped up, and it's supposed to be higher level than TinyTDS. 

Regardless, I appreciate that you share you expertise with SQL Server to the Ruby community. Thanks!

**Comment by metaskills** [comment] 2017-03-04 02:49
I do agree that this would be good for the Sequel team to adopt in their adapter. I saw this list today on Microsoft's site.

<img width="868" alt="screen shot 2017-03-03 at 6 54 25 pm" src="https://cloud.githubusercontent.com/assets/2381/23575500/4c123d48-005b-11e7-87bb-3dc01c5f3e3c.png">
