### ISSUE TITLE
Working only with Ruby < 2.6

### ISSUE THREAD

**Issue by lflucasferreira** [rails-sqlserver/tiny_tds#458] opened 2020-02-18 21:19 UTC
I don't know if this project is still under development, but I believe it could be updated in order to work with to the stable version, I mean 2.6.4.

$ gem install tiny_tds
Fetching tiny_tds-2.1.2-x64-mingw32.gem
ERROR:  Error installing tiny_tds:
        The last version of tiny_tds (>= 0) to support your Ruby & RubyGems was 2.1.2. Try installing it with `gem install tiny_tds -v 2.1.2`
        tiny_tds requires Ruby version >= 2.0, < 2.6. The current ruby version is 2.6.4.104.

**Comment by aharpervc** [comment] 2020-02-18 23:31
Dupe of https://github.com/rails-sqlserver/tiny_tds/issues/434, being worked on here https://github.com/rails-sqlserver/tiny_tds/pull/456

**Comment by cshtdd** [comment] 2020-02-19 20:11
I got `tiny_tds` working with ruby 2.6.5 on MacOS and CentOS7

I followed the steps described here

https://stackoverflow.com/questions/7525109/ror-unable-to-install-tiny-tds

It seems like there's a dependency on the `freetds` package

**Comment by Castone22** [comment] 2020-03-02 11:52
This only mostly applies to windows, since the gem tries to distribute tiny tds binaries when it's building on mingw based systems.  On unix flavors it seems to work fine in 2.6+ as long as the freetds library is available, though the version of the gem that installs is version 2.0.0, which is a tad outdated, be advised. @cshtdd

**Comment by aharpervc** [comment] 2020-04-08 20:24
I have pushed `2.1.3-pre` to rubygems for testing. Interested parties should install it & verify it works in ruby 2.6 with their app

**Closed** 2020-09-28 15:21 UTC

**Comment by aharpervc** [comment] 2020-09-29 13:51
2.1.3 has now been released
